# Generated by Django 5.2.17 on 2026-09-19 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('summary', models.TextField()),
                ('text', models.TextField(blank=True)),
                ('image_prompt', models.TextField(blank=True)),
                ('moderation_flag', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=80)),
                ('child_appearance', models.CharField(max_length=500)),
                ('favorite_theme', models.CharField(max_length=200)),
                ('reading_level', models.CharField(choices=[('beginner', 'Beginner (ages 3-5)'), ('early-reader', 'Early reader (ages 6-8)'), ('confident-reader', 'Confident reader (ages 9+)')], max_length=32)),
                ('moral_lesson', models.CharField(max_length=300)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OUTLINE_READY', 'Outline ready'), ('GENERATING', 'Generating'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('provider', models.CharField(max_length=100)),
                ('storage_path', models.CharField(max_length=500)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='stories.page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='stories.story'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('story', 'page_number'), name='unique_story_page'),
        ),
    ]
