# Generated by Django 5.2.17 on 2026-09-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='child_gender',
            field=models.CharField(choices=[('girl', 'Girl'), ('boy', 'Boy'), ('nonbinary', 'Non-binary / other'), ('unspecified', 'Prefer not to say')], default='unspecified', max_length=20),
        ),
    ]
