# Generated by Django 5.2.17 on 2026-09-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0002_story_child_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="reading_level",
            field=models.CharField(
                choices=[
                    ("toddler", "Toddlers (ages 0-2)"),
                    ("beginner", "Beginner (ages 3-5)"),
                    ("early-reader", "Early reader (ages 6-9)"),
                    ("confident-reader", "Confident reader (ages 10+)")
                ],
                max_length=32,
            ),
        ),
    ]