# Generated by Django 5.2.17 on 2026-09-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0003_alter_story_reading_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="story",
            name="publish_token_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]